const mongoose = require('mongoose')
var config = require('config')

//const mongoUri = `mongodb://${config.get('db.user')}:${config.get('db.password')}@${ config.get('db.host')}:${config.get('db.port')}/${config.get('db.database')}`
//mongoose.connect(mongoUri, {useNewUrlParser: true}).connection
const Schema = mongoose.Schema
const lepidopteraModel = new Schema({
        "lepBin": String,
        "adultLiveWtG": String,
        "adultVoucherFate": String,
        "amnhCode": String,
        "anotherPara": String,
        "barcodeLength": String,
        "barcodeWithN": String,
        "class": String,
        "collectedGroup": String,
        "collectedGroupTrait": String,
        "collectionDate": Date,
        "collector": String,
        "continent": String,
        "country": String,
        "dateDnaSample": String,
        "dateStamp": Date,
        "detHerb": String,
        "detHost": String,
        "detHyperpara": String,
        "detPara": String,
        "dhjPlantColl": String,
        "dhjParVoucher": String,
        "dnaSampleTo": String,
        "east": String,
        "elevation": String,
        "entry": String,
        "forewingLengthMm": String,
        "foundAs": String,
        "fpdes": String,
        "gelatinCapsuleToWhom": String,
        "herbEcloDate": Date,
        "herbPrepDate": Date,
        "herbPupDate": Date,
        "herbivoreComment": String,
        "herbivoreFamily": String,
        "herbivoreGenBankAcc": String,
        "herbivoreGenusName": String,
        "herbivoreSex": String,
        "herbivoreSpecies": String,
        "herbivoreSubfamily": String,
        "herbivoreTribe": String,
        "hostFamily": String,
        "hhostSpecies": String,
        "hyperBin": String,
        "hyperDhjParVoucher": String,
        "hyperparasiteFamily": String,
        "hyperparasiteSpecies": String,
        "hyperparasiteSubfamily": String,
        "idenBasisHerb": String,
        "idenBasisHost": String,
        "idenBasisPara": String,
        "immatureParts": String,
        "kingdom": String,
        "latitude": String,
        "locality": String,
        "longitude": String,
        "mostRecentDateNjTreeIdentified": String,
        "multiple": String,
        "north": String,
        "numberWithinYear": String,
        "order": String,
        "otherVoucherNumber": String,
        "paraBin": String,
        "parasiteFamily": String,
        "parasiteGenusName": String,
        "parasiteOrder": String,
        "parasiteSpecies": String,
        "parasiteSubfamily": String,
        "parasiteTribe": String,
        "photo": String,
        "phylum": String,
        "plantNickname": String,
        "primaryEcosystem": String,
        "province": String,
        "pupalLiveWtG": String,
        "rearingOutcome": String,
        "scannedPhoto": String,
        "search": String,
        "secondaryEcosystem": String,
        "sector": String,
        "specimenDepositedAt": String,
        "stage": String,
        "standardUnit": String,
        "subtribe": String,
        "timeStamp": String,
        "type": String,
        "voucher": String,
        "whenEnter": Date,
        "whoEnterData": String,
        "year": Date
    }
    , {strict: false});

module.exports = mongoose.model('lepidoptera', lepidopteraModel)
